### ISSUE TITLE
trimatu/trimatl option to include/remove diagonal

### ISSUE THREAD

**Issue by coatless** [conradsnicta/armadillo-code#25]
Presently both `trimatu` and `trimatl` return a triangular matrix _with_ the diagonal. It would be nice to offer the option to allow the exclusion of the diagonal. The present workaround I use is:

```cpp
arma::mat res = trimatl(Omega) - diagmat(Omega);
```

**Comment by conradsnicta** [comment]
It would be better to make this more general, by specifying how many diagonals above/below the main diagonal to keep.

**Comment by coatless** [comment]
So, mimic [`diagmat`](http://arma.sourceforge.net/docs.html#diagmat)'s `k` implementation?

**Comment by conradsnicta** [comment]
@coatless - implemented in Armadillo 7.950:
http://arma.sourceforge.net/docs.html#trimat
http://sourceforge.net/projects/arma/files/armadillo-7.950.1.tar.xz

**Comment by coatless** [comment]
@conradsnicta you are my hero! Thank you.  The availability of this option has been immediately pounced upon c.f. [SO answer](https://stackoverflow.com/a/44509604/1345455).

Though, at some point I would like to try and contribute some code to the main library as I'm frequently using armadillo in projects that I develop. **Do you have any recommendations for developing for the armadillo codebase outside of digging into the expression templating?** The [FAQ's development section](http://arma.sourceforge.net/faq.html#development) is relatively sparse outside of  the standard disclaimer for unit tests and documentation.

**Comment by conradsnicta** [comment]
@coatless - currently the best bet is to have a look at the implementation of several functions to see what's going on. when I have some bandwidth I'll look at describing the internals. the main things to watch out for are aliasing (eg. output matrix is an alias of one of the input matrices) and handling of matrices with integers or complex numbers (eg. what happens when cx_mat is used with a given function).
