### ISSUE TITLE
Copy/construct complex objects into/from real objects

### ISSUE THREAD

**Issue by titaschanda** [conradsnicta/armadillo-code#28]
Is it possible to copy/construct complex objects into/from real objects. for example:

    mat A = something;
    mat B = something;
    cx_mat C = A;
    cx_mat D = A+B;

It is not possible in the current version, but can I tweak the code to have such functionality, specially with Mat and Cube classes?

As per I remember, it was there in some earlier version.

**Comment by conradsnicta** [comment]
It's possible to use [conv_to](http://arma.sourceforge.net/docs.html#conv_to) or [.set_real()](http://arma.sourceforge.net/docs.html#set_imag).

Otherwise the Mat class can be extended with an explicit constructor. It would involve a small degree of meta-programming, as the Mat class is a template for both the `mat` and `cx_mat` type. There is a risk that dodgy compilers (like the garbage known as MSVC) can choke on such a constructor.

**Comment by titaschanda** [comment]
Yes, ``conv_to`` can be used, but to use ``cx_mat`` in some other predefined libraries, such constructor is needed. Since, MSVC (and windows) is not a problem, I may write such explicit constructor. Thank you, for the advice. 
:)
