### ISSUE TITLE
LAPACK not enabled even though openBLAS is used

### ISSUE THREAD

**Issue by knedlsepp** [conradsnicta/armadillo-code#30]
openBLAS contains LAPACK routines by default. Building armadillo against openBLAS however does not activate the USE_LAPACK functionality.
It seems one can forcefully enable this by using:
```
cmake -DLAPACK_LIBRARY=/path/to/libopenblas.so
```
This shouldn't however be necessary. This could be done by using cmake's(>=3.6.0) `FindLAPACK`, which will find openBLAS when looking for LAPACK.

**Comment by conradsnicta** [comment]
> openBLAS contains LAPACK routines by default.

Unfortunately that can't be guaranteed, because the super-wise folks at Debian build their version of OpenBLAS without LAPACK.  Debian stuff then propagates to Ubuntu, and we end up with a royal mess.  

Armadillo needs to support various Linux-based operating systems, so we can't assume OpenBLAS comes with LAPACK built in.  I suggest filing a bug with the Debian folks.  Maybe they'll reconsider their rather questionable decision.

**Comment by eddelbuettel** [comment]
The openblas package contains a lapack version, as do the available alternatives, and have for as long as I can remember.

```sh
edd@bud:~$ dpkg -L libopenblas-base
/.
/usr
/usr/lib
/usr/lib/openblas-base
/usr/lib/openblas-base/libblas.so.3
/usr/lib/openblas-base/liblapack.so.3
/usr/lib/libopenblasp-r0.2.18.so
/usr/share
/usr/share/doc
/usr/share/doc/libopenblas-base
/usr/share/doc/libopenblas-base/copyright
/usr/share/doc/libopenblas-base/changelog.Debian.gz
/usr/share/doc/libopenblas-base/README.Debian
/usr/share/doc/libopenblas-base/TODO.Debian
/usr/lib/libopenblas.so.0
edd@bud:~$ 
```

**Comment by conradsnicta** [comment]
@eddelbuettel - does that require linking with the openblas-base version of lapack?
ie. /usr/lib/openblas-base/liblapack.so.3

The issue here is that we can't seem to assume that /usr/lib/libopenblasp-r0.2.18.so contains lapack functions.

**Comment by eddelbuettel** [comment]
All that is resolved just fine at the operating system and has since Camm set this up in the late 1990s, your griping notwithstanding.  Methinks you're just wrong.  But happy to be convinced otherwise.

From installing RcppArmadillo:

```
g++ -shared -L/usr/lib/R/lib -Wl,-Bsymbolic-functions -Wl,-z,relro -o RcppArmadillo.so \
    RcppArmadillo.o RcppExports.o fastLm.o -fopenmp -llapack -lblas -lgfortran -lm -lquadmath \
    -L/usr/lib/R/lib -lR
```

**Comment by eddelbuettel** [comment]
So to expand on this: basically users have a choice between several (three, these days, AFAIK) BLAS/LAPACK implementations all of which are setup such that you can just switch between them.  It _only ever requires `-llapack -lblas` and nothing else_.  I once used this scheme for a comparison benchmarking paper draft (as a vignette in package [gcbd](https://cloud.r-project.org/web/packages/gcbd/index.html)).

**Comment by conradsnicta** [comment]
Linking with -lblas -llapack is not the problem. Debian can redirect the libraries to wherever it wants, as long as it actually provides blas and lapack functions. The underlying issue is that by linking only with -lopenblas (without -llapack), there is no guarantee that lapack functions will be present.

It's been a while since I checked this (maybe Ubuntu  12.04 ?), so things may have changed, but I had lots of bug reports when the Armadillo runtime library was linking only with -lopenblas.  Adding in -llapack resolved the problem, and I don't have the patience nor the time to chase down the bazillion differences between various Linux-based operating systems.

**Comment by knedlsepp** [comment]
I was not aware of openBLAS possibly excluding LAPACK. This problem however could be resolved by using https://github.com/Kitware/CMake/blob/master/Modules/FindLAPACK.cmake instead of the custom https://github.com/conradsnicta/armadillo-code/blob/unstable/cmake_aux/Modules/ARMA_FindLAPACK.cmake.
The new cmake FindLAPACK should pick up LAPACK from openBLAS iff it's included.

**Comment by conradsnicta** [comment]
Yeah, the custom ARMA_FindLAPACK was first written eons ago, when CMake didn't have FindLAPACK.  Given that the Armadillo installer now requires CMake 2.8.12 at minimum, maybe it's time to update it to use the newer FindLAPACK.

**Comment by knedlsepp** [comment]
CMake itself ships the openBLAS support in FindLAPACK only since 3.6.0, so if we don't want a huge CMake version bump the best alternative would probably to replace the ARMA_FindLAPACK.cmake with theirs. (If licensing is not an issue, which I don't know much about.)
