### ISSUE TITLE
Save multiple datasets to a single hdf5 file

### ISSUE THREAD

**Issue by JWichmann** [conradsnicta/armadillo-code#41]
Hi,
I would like to save multiple datasets to a single hdf5 file.
So I wrote a patch to add this functionality to armadillo.

Here is a short overview of what the patch does:
1. It does not break any existing code (as far as I can tell, and I have done quite a bit of testing).
2. The code adds another parameter which can optionally be passed to .save(hdf5_name(filename, dataset, APPEND), file_type)
3. If append is set to 1, then the dataset will be appended to an existing hdf5 file. If the file does not exist it will be created.
4. The user needs to make sure not to append a dataset with a name that is already used as dataset in the hdf5 file. If such a mistake is made an error message will be printed, stating both the offending dataset name and the file name.

This is my first contribution to a big project, so please tell me how to improve my patch in order to get it merged

Thanks,
Jan

[multiple_datasets_patch.txt](https://github.com/conradsnicta/armadillo-code/files/1458339/multiple_datasets.txt)

**Comment by conradsnicta** [comment]
Hi Jan, thanks for the contribution.  To make it easier to review and merge the proposed code, I would suggest you fork the armadillo-code repo, incorporate your changes, and then submit a pull request.

I have a few quick observations on the proposed patch:
 - please use the `bool` type instead of `int` for indicator variables wherever possible (ie. `const bool overwrite`)
- each project uses its own style format; for multi-line expressions Armadillo generally follows the [Whitesmiths indentation](https://en.wikipedia.org/wiki/Indentation_style#Whitesmiths_style) style; the main reasoning is to reduce the cognitive load when writing heavy template code.
- don't pack too many conditions in an `if` statement; it's preferable to split the conditions into multiple `if` statements, in order to have clearer paths of execution

**Comment by JWichmann** [comment]
Hi,
thanks for the swift response. I fixed your issues and am now working on the tests. I am looking into the tests to see if I need to add any more for regression checking. For the new functionality tests I have a question. Should I only test for the intended use, or also try to come up with a test that ensures that error handling is correct? For the latter I would have to check the output to stdout or stderr, so I might need a bit to figure that out.

**Comment by conradsnicta** [comment]
The more tests the better, so it would be good to check the error handling as well.

**Comment by conradsnicta** [comment]
@rcurtin - I've refactored the append code to take into account potential group hierarchy. Could you have a quick look to see whether the hdf5 spaghetti still makes sense? https://github.com/conradsnicta/armadillo-code/commit/badc4bbb6c9bac6b3614f3e699de7a478d059768

@JWichmann - I've changed the code to use an explicit `hdf5_opts::append` argument instead of a simple `bool`. This has two effects:
1. Someone reading user code that saves hdf5 files is more likely to understand what's going on, instead of guessing what `true` means
2. Further options can be easily added, to allow things such as replacing existing datasets, etc.

**Comment by JWichmann** [comment]
@conradsnicta - Just tested it with my use case. Works great! Now three questions arise:

1. In my pull request I used `arma_warn` if a dataset was to be written with an already existing name. In this warning I printed the name of the duplicate dataset so the user could find the offending line in his code quicker. Should something like this be added again?
2. Now that you introduced `hdf5_opts`, should this be used to save matrices in transposed format? While this would be more consistent, it would also break existing code to remove the `hdf5_binary_trans` option.
3. I noticed that no error message is given if we `#define ARMA_NO_DEBUG` and try to write two datasets with the same name. The program only saves one of the two datasets and continues as if nothing had happened. Now I know that any user should always test his program in debug mode, but still I am no fan of silent failing.

**Comment by conradsnicta** [comment]
@JWichmann 

> In my pull request I used arma_warn if a dataset was to be written with an already existing name. In this warning I printed the name of the duplicate dataset so the user could find the offending line in his code quicker. Should something like this be added again?

Yes, but the warning should be printed in the Mat::save() and Cube::save() functions instead of directly in the diskio::save_hdf5_binary() functions. The save() functions have an optional parameter to not print anything.

> Now that you introduced hdf5_opts, should this be used to save matrices in transposed format? While this would be more consistent, it would also break existing code to remove the hdf5_binary_trans option.

Yeah, it would be useful to add a transpose option to hdf5_opts. Explicitly removing support for the hdf5_binary_trans format is not possible, as it would break existing user code. Armadillo has a strict API policy: http://arma.sourceforge.net/docs.html#api_additions. However, the description of hdf5_binary_trans can be removed from the documentation in order to encourage the use of the hdf5_opts mechanism in new user code.

> I noticed that no error message is given if we #define ARMA_NO_DEBUG and try to write two datasets with the same name. The program only saves one of the two datasets and continues as if nothing had happened. Now I know that any user should always test his program in debug mode, but still I am no fan of silent failing.

The save() function should still fail -- it outputs a bool set to false.  It's up to the user to explicitly check the condition instead of relying on warning messages. The vast majority of warning messages are disabled if ARMA_NO_DEBUG is enabled.

**Comment by conradsnicta** [comment]
@JWichmann - I've extended the code to allow replacement of datasets, as well as more detailed debugging messages.  Can you test it on your end?

**Comment by JWichmann** [comment]
I tested the replacement of datasets. Works for me. I will write some more tests for it tomorrow.
Your debug message works, too.
I might also start to work on documentation changes, but need to understand all your changes first. Not that c++ adept yet, more into science than IT.
